- name: install java
  apt:
    name: openjdk-8-jdk
    state: present
  sudo: yes

- name: set JAVA_HOME
  lineinfile:
    dest: .bashrc
    line: 'export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"'
