- name: transfer the ssh keys
  copy:
    src: "{{ local_home }}/.ssh/aws/{{ item }}"
    dest: "/home/{{ ansible_ssh_user }}/.ssh/"
    mode: 0600
  with_items:
    - "id_rsa"
    - "id_rsa.pub"

- name: ensure github.com is a known host
  lineinfile:
    dest: "/home/{{ ansible_ssh_user }}/.ssh/known_hosts"
    create: yes
    state: present
    line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
    regexp: "^github\\.com"

- name: copy the aws keys
  copy:
    src: "{{ local_home }}/.ssh/aws"
    dest: "/home/{{ ansible_ssh_user }}/.ssh/"
    mode: 0600
